# Site settings
title: "Blood Bank Management System"
description: "A web application connecting patients, donors, and blood banks for efficient blood donation and request management."

# Theme settings
remote_theme: pages-themes/minimal@v0.2.0

# Plugin settings
plugins:
  - jekyll-remote-theme

# Display settings
show_downloads: false
show_title: false
